version: '3'
services:
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: saiaunghlyanhtet
      MYSQL_DATABASE: users_crud
    ports:
      - "3307:3306"

  app:
    image: emp-data:1.0.1
    ports:
      - "8080:8080"
    depends_on:
      - db
